version: "3.3"
services:
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      labels:
        build.commit: ${BUILD_COMMIT}
        build.date: ${BUILD_DATE}
    image: ekyc/api:latest
