version: '3'
services:
  api-ekyc:
    image: ekyc/api:latest
    environment:
        - SERVER_PORT=xxxx
        - API_SERVER_ADDRESS=xxxx
    entrypoint: /api/docker/start-api.sh
    volumes:
        - ./start-api.sh:/api/docker/start-api.sh:ro
    ports:
      - "4000:3000"

    networks:
      - ekyc-network
networks:
  ekyc-network:
